---
- hosts: devlinux
  user: ansible
  become: yes


  tasks:
    - name: install apache
      action: yum pkg=httpd state=present
      notify:
        - start
        - deploy

  handlers:
    - name: start
      action: service name=httpd state=started

    - name: deploy
      action: copy src=index.html dest=/var/www/html
