--- #variable
- hosts: devlinux
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    pkgname: httpd
    index_path: /var/www/html

  tasks:
    - name: install apache
      action: yum pkg="{{pkgname}}" state=present

    - name: state apache
      action: service name="{{pkgname}}" state=started
     
    - name: copy index
      action: copy src=index.html dest="{{index_path}}"


- hosts: qalinux
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  vars: 
    pkgname: tree

  tasks: 
    - name: install tree
      action: yum pkg="{{pkgname}}" state=present

